name: On release

on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  release:
    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build
        run: |
          docker buildx build -f docker/Dockerfile.build --output type=local,dest=out/ ./hailort/
      - name: Upload release artifacts
        if: ${{ github.event_name == 'release' }}
        run: |
          shopt -s globstar
          for filename in out/**/*.tar.gz out/**/*.whl; do
            [ -e "$filename" ] || continue
            gh release upload ${{github.event.release.tag_name}} "$filename"
          done
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}
        shell: bash
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        if: ${{ github.event_name != 'release' }}
        with:
          name: release-${{ matrix.os }}
          path: |
            out/**/*.tar.gz
            out/**/*.whl
